# Generated by Django 6.0.3 on 2026-04-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='user',
                    table='users',
                ),
            ],
        ),
    ]
