# Generated by Django 4.2.26 on 2026-04-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('frontend', 'Frontend Department'), ('backend', 'Backend Department'), ('database', 'Database Department'), ('cybersecurity', 'Cybersecurity Department')], default='frontend', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('manager', 'Manager')], default='member', max_length=16),
        ),
        migrations.CreateModel(
            name='DepartmentJoinRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_department', models.CharField(choices=[('frontend', 'Frontend Department'), ('backend', 'Backend Department'), ('database', 'Database Department'), ('cybersecurity', 'Cybersecurity Department')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to='api.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='api.user')),
            ],
            options={
                'db_table': 'department_join_requests',
            },
        ),
    ]
