# Generated by Django 4.2.26 on 2026-04-30 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_account_status_user_department_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='focus_end_line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='focus_start_line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='low', max_length=16),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='priority_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='priority_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_updates', to='api.user'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='scan_input_type',
            field=models.CharField(choices=[('file', 'File upload'), ('paste', 'Pasted code'), ('text', 'Text question')], default='file', max_length=16),
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('purple', 'Purple'), ('blue', 'Blue')], default='dark', max_length=20)),
                ('ai_model', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.user')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.codesubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='api.user')),
            ],
            options={
                'db_table': 'report_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
