# Generated by Django 4.2.26 on 2026-04-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_codesubmission_focus_end_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='report_title',
            field=models.CharField(blank=True, default='', help_text='User-facing name for this report (optional).', max_length=200),
        ),
    ]
