# Generated by Django 6.0.3 on 2026-04-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_table'),
        ('api', '0003_codesubmission_report_data'),
    ]

    operations = [
    ]
