# Generated by Django 6.0.3 on 2026-04-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20260422_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cwe',
            options={'managed': False},
        ),
    ]
