# Generated by Django 6.0.3 on 2026-04-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cwe_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cwe',
            table='cwe',
        ),
    ]
