# Generated by Django 6.0.3 on 2026-04-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cwe_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='codesubmission',
            table='code_submissions',
        ),
    ]
